name: Release

on: 
  push:
    tags:
      - "v*.*.*"

env:
  FILENAME: thesis 
jobs:
  build:
    name: Build LaTex File
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTex Document
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            pdflatex -synctex=1 -interaction=nonstopmode ${{ env.FILENAME }}.tex
            makeindex -s nomencl.ist -t ${{ env.FILENAME }}.nlg -o ${{ env.FILENAME }}.nls ${{ env.FILENAME }}.nlo
            pdflatex -synctex=1 -interaction=nonstopmode -jobname=${{ env.FILENAME }}-${{ github.ref_name }} ${{ env.FILENAME }}.tex
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.FILENAME }}-${{ github.ref_name }}
          path: ./${{ env.FILENAME }}-${{ github.ref_name}}.pdf

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.FILENAME }}-${{ github.ref_name }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.FILENAME }}-${{ github.ref_name }}.pdf
