name: Release

on: 
  push:
    branches:
      - main
    tags:
      - v*.*.*
      
jobs:
  build:
    name: Build LaTex File
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTex Document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: thesis.tex
      - uses: actions/upload-artifact@v3
        with:
          name: thesis 
          path: ./thesis.pdf

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: thesis
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: thesis.pdf
