name: Release

on: 
  push:
    tags:
      - "v*.*.*"
      
jobs:
  build:
    name: Build LaTex File
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTex Document
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            pdflatex -synctex=1 -interaction=nonstopmode thesis.tex
            makeindex -s nomencl.ist -t thesis.nlg -o thesis.nls thesis.nlo
            pdflatex -synctex=1 -interaction=nonstopmode -jobname=thesis-${{ github.ref_name }} thesis.tex
      - uses: actions/upload-artifact@v3
        with:
          name: thesis-${{ github.ref_name }}
          path: ./thesis-${{ github.ref_name}}.pdf

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: thesis-${{ github.ref_name }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: thesis.pdf
